### PR TITLE
Native modules

### PR DESCRIPTION
**Pull request by stsvilik**
## Description
This PR removes redundant dependencies such as `colorLogger` in favor of `@wdio/logger` and also gets rid of `bluebird` in favor of native `Promise`.

- Additionally tests are rewritten to use `async/await` and `chai`
- `debug` flag in configuration is deprecated in favor of `logLevel`

## Checklist
- [ ] Unit/Integration test added (if applicable)
- [X] Documentation added/updated (wiki or md)
- [X] Code style is consistent with the rest of the project

### CODE REVIEW

**Comment by serbanghita** [comment]
LGTM , great job! 👍

**Comment by serbanghita** [comment]
@stsvilik After this I can actually start debugging the test Promise errors. Last time I got lost in the `bluebird` stack.
I can create a separate issue for these:

```
(node:1188) UnhandledPromiseRejectionWarning: undefined
(node:1188) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by stsvilik** [comment]
@serbanghita I think those are not a problem - it is caused by using `sinon` stubs and returning `Promise.reject()`

**Comment by stsvilik** [comment]
@serbanghita I fixed those pesky Promise errors ;)

**Comment by serbanghita** [comment]
@stsvilik great job! 🍾

**Comment by serbanghita** [comment]
@stsvilik do you release the tag manually in npm?

**Comment by stsvilik** [comment]
manually

**Pull request merged**
