### PR TITLE
feat: Support wdio v6

### PR DESCRIPTION
**Pull request by hieuxlu**
## Description
- Bump wdio version
- Add path property in config (or capabilities) to integration test to support wdio v6 (or host Chrome will be launched instead)

## Checklist
- [X] Unit/Integration test added (if applicable)
- [X] Documentation added/updated (wiki or md) https://github.com/hieuxlu/wdio-docker-service.wiki.git
- [X] Code style is consistent with the rest of the project

### CODE REVIEW

**Comment by hieuxlu** [comment]
@stsvilik The cached node_modules directory needs to be manually cleared for this PR. I don't have permission to do that. 
https://docs.travis-ci.com/user/caching/#pull-request-builds-and-caches

**Comment by stsvilik** [comment]
@hieuxlu LGTM, I would however bump package version as well to have clear distinction between supported WDIO versions. Could you make it `3.0.0` ? ( just run `npm version major`).

**Comment by stsvilik** [comment]
@hieuxlu Test seem to fail even with cache cleared

**Comment by hieuxlu** [comment]
@stsvilik Ah weird, it succeeded locally. I'll have a look. And yes it's a major bump.

**Comment by hieuxlu** [comment]
@stsvilik It seems like the integration tests are flaky. The failure appears on latest builds as well, not only this PR. After clearing caches, all unit tests passed btw, so it's a problem with flaky integration tests.

**Comment by hieuxlu** [comment]
Yay, it's green, told you so @stsvilik I'm gonna update the wiki later to add `path: '/wd/hub'` to sample config for wdio v6

**Comment by hieuxlu** [comment]
@stsvilik I bumped major version and updated the wiki page in this repo https://github.com/hieuxlu/wdio-docker-service.wiki.git , because Github does not allow a PR to a wiki repo. Please have a look, thanks.

**Review by stsvilik — APPROVED** [review]

**Comment by stsvilik** [comment]
@hieuxlu Sorry for delay - I fried my computer and couldn't get it repaired for a while. I merged and published your PR, but don't seem to have access to your wiki. Could you include the content as a comment maybe, and I'll create a page in this repo?

**Comment by hieuxlu** [comment]
@stsvilik Can you try clone my wiki locally. It seems to be the only way to merge wiki
https://github.com/hieuxlu/wdio-docker-service.wiki.git
Here's the diff (but the Github wiki diff view is also not working properly)
https://github.com/hieuxlu/wdio-docker-service/wiki/Selenium-Docker:-Testing-local-applications/_compare/15bec4273351af2b4ba18c25c06df05d87e292a4

**Comment by hieuxlu** [comment]
The wiki repo is not supposed to be accessiable via web page. Did you try `git clone https://github.com/hieuxlu/wdio-docker-service.wiki.git`, because I cloned yours just the same.

**Comment by stsvilik** [comment]
Yes, got it. Thanks.

**Pull request merged**
